### PR TITLE
Resolves issue #19 and #18

### PR DESCRIPTION
**Pull request by abetusk**
* Rotates mask
* takes out spurious 'f' characters that somehow got introduces into the `argparams.py` file

### CODE REVIEW

**Comment by BernardZhao** [comment]
Thanks for this! I forgot to rotate the mask as well. Solves #19.

As for the f characters, those are Python f-Strings, which allows for the expressions in the brackets to be evaluated, and they aren't actually random. This is a feature in Python 3.6 and above, which is why #18 gave an error.

**Comment by abetusk** [comment]
I see. The Python3 f-Strings break what would otherwise be a functioning script for (on my system) Python 2.7.12 and Python 3.5.2.

Can we either agree to take the f-Strings out for now or put in something else to ensure some semblance of backwards compatibility?

**Comment by BernardZhao** [comment]
Sure, I'm completely fine with just using normal string formatting to ensure backwards compatibility. I'm glad you brought this up, since at the time when I suggested the change, I didn't get any input from others, so I just went ahead and used them.

We can replace all the f-strings with `'Hello, {}'.format(name)` formatting, and it should work with both Python 2 and 3.

**Comment by abetusk** [comment]
ok, there should be an updated version with correct formatting.

I couldn't trigger the case in `verify_args` that logs a warning about the default output path ([line 99](https://github.com/satyarth/pixelsort/blob/af85da1a513a98e5caec36bc030ab05ca96f1411/argparams.py#L99)) but otherwise I hope it's ok.

Are we waiting on @satyarth to merge?

I should have been paying attention more closely but I only tend to invest in bug fixing and other traffic when I actually use this tool so that's why I'm only noticing now. In the future I'll try and be better about staying on top of what's going on.

Maybe we should get a gallery of people using this tool so we can encourage people to pay attention more...

**Comment by satyarth** [comment]
Looks good, thanks @abetusk and @BernardZhao !

**Pull request merged**
